# Auto-generated by ./BuildEnv
if [ -z "$WORKSPACE" ]
then
  export WORKSPACE=/usr/local/UDK2014/MyWorkSpace
fi
if [ -z "$EDK_TOOLS_PATH" ]
then
  export EDK_TOOLS_PATH=/usr/local/UDK2014/MyWorkSpace/BaseTools
fi
if [ -e /usr/local/UDK2014/MyWorkSpace/BaseTools/Bin/Linux-x86_64 ]
then
  if [ ${PATH//usr/local/UDK2014/MyWorkSpace/BaseTools/Bin/Linux-x86_64/} == $PATH ]
  then
    export PATH=/usr/local/UDK2014/MyWorkSpace/BaseTools/Bin/Linux-x86_64:$PATH
  fi
fi
